import { useState } from 'react';
import { useStore, getDefaultPersona } from '../store/useStore';
import type { Persona } from '../types';
import { Check } from 'lucide-react';
import { Briefcase, User, Store, Code, Heart, DollarSign, Shield, Palette, Truck, Stethoscope, Mic, GraduationCap, Building2, Film, Music, Utensils, FlaskConical, Plane, PawPrint, Baby, Gamepad2, BookOpen, Bitcoin, Laptop, Mail, Search, ShoppingCart, Video, Camera, Smartphone, Cloud, Cpu, Database, Headphones, PenTool, Target, Zap, Award, Globe, MessageSquare, FileText, Coffee, Users } from 'lucide-react';

const avatarPool = [
  'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&h=150&fit=crop&crop=faces',
  'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&h=150&fit=crop&crop=faces',
  'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&h=150&fit=crop&crop=faces',
  'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&h=150&fit=crop&crop=faces',
  'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=faces',
  'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=faces',
  'https://images.unsplash.com/photo-1438761681033-6461ffad8d84?w=150&h=150&fit=crop&crop=faces',
  'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&h=150&fit=crop&crop=faces',
  'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&h=150&fit=crop&crop=faces',
  'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&h=150&fit=crop&crop=faces',
  'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=150&h=150&fit=crop&crop=faces',
  'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&h=150&fit=crop&crop=faces',
  'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&h=150&fit=crop&crop=faces',
  'https://images.unsplash.com/photo-1552058544-f2b08422138a?w=150&h=150&fit=crop&crop=faces',
  'https://images.unsplash.com/photo-1502685104226-ee32379fefbe?w=150&h=150&fit=crop&crop=faces',
  'https://images.unsplash.com/photo-1541862702-474f8a31e288?w=150&h=150&fit=crop&crop=faces',
  'https://images.unsplash.com/photo-1552374196-1ab2b1b33cad?w=150&h=150&fit=crop&crop=faces',
  'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=150&h=150&fit=crop&crop=faces',
  'https://images.unsplash.com/photo-1492562084223-fc5f1b0b6c7e?w=150&h=150&fit=crop&crop=faces',
  'https://images.unsplash.com/photo-1519345182560-3f4bc410562?w=150&h=150&fit=crop&crop=faces',
  'https://images.unsplash.com/photo-1502823403499-6ccfcf4fb8d8?w=150&h=150&fit=crop&crop=faces',
  'https://images.unsplash.com/photo-1463453091185-61582044d556?w=150&h=150&fit=crop&crop=faces',
  'https://images.unsplash.com/photo-1529665253569-6d01c1e1bc19?w=150&h=150&fit=crop&crop=faces',
  'https://images.unsplash.com/photo-1488426862026-3ee6a9cdd7ea?w=150&h=150&fit=crop&crop=faces',
  'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=faces',
  'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop&crop=faces',
  'https://images.unsplash.com/photo-1513952569396-e2969d3f5b44?w=150&h=150&fit=crop&crop=faces',
  'https://images.unsplash.com/photo-1501386761578-eac5c95b5c61?w=150&h=150&fit=crop&crop=faces',
  'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=150&h=150&fit=crop&crop=faces',
  'https://images.unsplash.com/photo-1528892952291-020c1ff8f63c?w=150&h=150&fit=crop&crop=faces',
  'https://images.unsplash.com/photo-1504198458649-3128b932f49e?w=150&h=150&fit=crop&crop=faces',
  'https://images.unsplash.com/photo-1485890426518-ddf5b821d1bf?w=150&h=150&fit=crop&crop=faces',
  'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=150&h=150&fit=crop&crop=faces',
  'https://images.unsplash.com/photo-1504439904031-93ded9f93e4f?w=150&h=150&fit=crop&crop=faces',
  'https://images.unsplash.com/photo-1448375240586-dfd8d395ea6c?w=150&h=150&fit=crop&crop=faces',
  'https://images.unsplash.com/photo-1473186578172-c211a16f7c26?w=150&h=150&fit=crop&crop=faces',
  'https://images.unsplash.com/photo-1503919005318-35e953b0437b?w=150&h=150&fit=crop&crop=faces',
  'https://images.unsplash.com/photo-1537368910025-700350fe46bc?w=150&h=150&fit=crop&crop=faces',
  'https://images.unsplash.com/photo-1519843012162-b3ee4d19c30d?w=150&h=150&fit=crop&crop=faces',
  'https://images.unsplash.com/photo-1504194921103-f8b80cadd5e4?w=150&h=150&fit=crop&crop=faces',
  'https://images.unsplash.com/photo-1502720705945-a61eac31491b?w=150&h=150&fit=crop&crop=faces',
  'https://images.unsplash.com/photo-1508962914676-e134849dd9c4?w=150&h=150&fit=crop&crop=faces',
  'https://images.unsplash.com/photo-1492106087820-71c95061ae85?w=150&h=150&fit=crop&crop=faces',
  'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&h=150&fit=crop&crop=faces',
  'https://images.unsplash.com/photo-1570211776045-5d50eaa51f4e?w=150&h=150&fit=crop&crop=faces',
  'https://images.unsplash.com/photo-1489987707025-afc2321057bc?w=150&h=150&fit=crop&crop=faces',
  'https://images.unsplash.com/photo-1542280756-74b2f55e73ab?w=150&h=150&fit=crop&crop=faces',
  'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop&crop=faces',
  'https://images.unsplash.com/photo-1492562084223-fc5f1b0b6c7e?w=150&h=150&fit=crop&crop=faces',
  'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=faces',
];

const templates = [
  {
    id: 'tech-executive',
    name: 'Tech Executive',
    description: 'C-level executive focused on ROI and innovation',
    category: 'Business',
    icon: Briefcase,
    avatar: avatarPool[0],
    traits: {
      name: 'Michael Torres',
      role: 'CTO',
      demographics: { age: '45', location: 'Seattle, WA', income: '$350,000', education: 'MS Computer Science' },
      background: 'Former startup founder, now scaling enterprise tech company.',
      personalityTraits: { openness: 70, conscientiousness: 85, extraversion: 55, agreeableness: 60, neuroticism: 25 },
      communicationStyle: 'Concise, strategic, bottom-line oriented',
      techSavvy: 90,
      preferredChannels: ['Email', 'LinkedIn', 'Executive briefings'],
      brandValues: ['Innovation', 'Scalability', 'Security'],
    },
  },
  {
    id: 'young-professional',
    name: 'Young Professional',
    description: 'Career-focused millennial seeking growth',
    category: 'Career',
    icon: User,
    avatar: avatarPool[1],
    traits: {
      name: 'Emma Wilson',
      role: 'Senior Designer',
      demographics: { age: '28', location: 'Austin, TX', income: '$85,000', education: 'BFA Design' },
      background: '5 years experience, climbing the design ladder at a fintech startup.',
      personalityTraits: { openness: 80, conscientiousness: 70, extraversion: 65, agreeableness: 75, neuroticism: 45 },
      communicationStyle: 'Creative, collaborative, visual',
      techSavvy: 80,
      preferredChannels: ['Slack', 'Figma', 'Video calls'],
      brandValues: ['Creativity', 'Work-life balance', 'Purpose'],
    },
  },
  {
    id: 'small-business',
    name: 'Small Business Owner',
    description: 'Hands-on entrepreneur managing all aspects',
    category: 'Entrepreneur',
    icon: Store,
    avatar: avatarPool[2],
    traits: {
      name: 'David Kim',
      role: "Owner's Bakery",
      demographics: { age: '42', location: 'Chicago, IL', income: '$75,000', education: 'Business Certificate' },
      background: 'Family bakery expanded to 3 locations over 8 years.',
      personalityTraits: { openness: 55, conscientiousness: 90, extraversion: 70, agreeableness: 85, neuroticism: 35 },
      communicationStyle: 'Friendly, local, personal',
      techSavvy: 45,
      preferredChannels: ['Phone', 'In-person', 'Facebook'],
      brandValues: ['Quality', 'Community', 'Tradition'],
    },
  },
  {
    id: 'software-engineer',
    name: 'Software Engineer',
    description: 'Technical problem-solver who values clean code',
    category: 'Technology',
    icon: Code,
    avatar: avatarPool[3],
    traits: {
      name: 'Alex Chen',
      role: 'Senior Software Engineer',
      demographics: { age: '31', location: 'San Francisco, CA', income: '$180,000', education: 'BS Computer Science' },
      background: '6 years at top tech companies, open-source contributor.',
      personalityTraits: { openness: 75, conscientiousness: 90, extraversion: 35, agreeableness: 65, neuroticism: 30 },
      communicationStyle: 'Technical, precise, asynchronous preferred',
      techSavvy: 95,
      preferredChannels: ['GitHub', 'Slack', 'Email'],
      brandValues: ['Clean code', 'Open source', 'Documentation'],
    },
  },
  {
    id: 'healthcare-professional',
    name: 'Healthcare Professional',
    description: 'Compassionate caregiver focused on patient outcomes',
    category: 'Healthcare',
    icon: Stethoscope,
    avatar: avatarPool[4],
    traits: {
      name: 'Dr. Sarah Mitchell',
      role: 'Family Physician',
      demographics: { age: '38', location: 'Denver, CO', income: '$195,000', education: 'MD from Johns Hopkins' },
      background: '12 years in private practice, focus on preventive care.',
      personalityTraits: { openness: 65, conscientiousness: 90, extraversion: 55, agreeableness: 90, neuroticism: 40 },
      communicationStyle: 'Empathetic, clear, patient-centered',
      techSavvy: 60,
      preferredChannels: ['Phone', 'In-person', 'Patient portal'],
      brandValues: ['Compassion', 'Excellence', 'Trust'],
    },
  },
  {
    id: 'marketing-manager',
    name: 'Marketing Manager',
    description: 'Creative strategist driving brand awareness',
    category: 'Marketing',
    icon: Palette,
    avatar: avatarPool[5],
    traits: {
      name: 'Jessica Rivera',
      role: 'Brand Marketing Manager',
      demographics: { age: '33', location: 'New York, NY', income: '$125,000', education: 'MBA Marketing' },
      background: 'Led campaigns for Fortune 500 companies.',
      personalityTraits: { openness: 85, conscientiousness: 75, extraversion: 80, agreeableness: 70, neuroticism: 35 },
      communicationStyle: 'Energetic, creative, story-driven',
      techSavvy: 75,
      preferredChannels: ['Slack', 'Video calls', 'Social media'],
      brandValues: ['Creativity', 'Authenticity', 'Impact'],
    },
  },
  {
    id: 'finance-professional',
    name: 'Finance Professional',
    description: 'Data-driven advisor managing wealth',
    category: 'Finance',
    icon: DollarSign,
    avatar: avatarPool[6],
    traits: {
      name: 'Robert Thompson',
      role: 'Wealth Manager',
      demographics: { age: '47', location: 'Boston, MA', income: '$275,000', education: 'MBA Finance, CFA' },
      background: '15 years in private banking, manages HNW portfolios.',
      personalityTraits: { openness: 50, conscientiousness: 95, extraversion: 45, agreeableness: 60, neuroticism: 20 },
      communicationStyle: 'Professional, data-driven, discreet',
      techSavvy: 70,
      preferredChannels: ['Phone', 'In-person', 'Secure email'],
      brandValues: ['Trust', 'Transparency', 'Results'],
    },
  },
  {
    id: 'startup-founder',
    name: 'Startup Founder',
    description: 'Visionary building the next big thing',
    category: 'Entrepreneur',
    icon: Code,
    avatar: avatarPool[7],
    traits: {
      name: 'Emily Zhang',
      role: 'CEO & Founder',
      demographics: { age: '29', location: 'Palo Alto, CA', income: '$150,000', education: 'Dropped out of Stanford CS' },
      background: 'Series A startup, previously founded 2 acqui-hired companies.',
      personalityTraits: { openness: 95, conscientiousness: 80, extraversion: 75, agreeableness: 55, neuroticism: 60 },
      communicationStyle: 'Visionary, persuasive, fast-paced',
      techSavvy: 90,
      preferredChannels: ['Twitter', 'LinkedIn', 'Video calls'],
      brandValues: ['Disruption', 'Speed', 'User focus'],
    },
  },
  {
    id: 'retail-manager',
    name: 'Retail Manager',
    description: 'Customer-focused store leader',
    category: 'Retail',
    icon: Truck,
    avatar: avatarPool[8],
    traits: {
      name: 'Marcus Johnson',
      role: 'Store General Manager',
      demographics: { age: '35', location: 'Atlanta, GA', income: '$65,000', education: 'BS Business' },
      background: '10 years in retail, transformed underperforming stores.',
      personalityTraits: { openness: 60, conscientiousness: 85, extraversion: 80, agreeableness: 75, neuroticism: 45 },
      communicationStyle: 'Approachable, direct, motivational',
      techSavvy: 55,
      preferredChannels: ['In-person', 'Team meetings', 'Text'],
      brandValues: ['Customer service', 'Teamwork', 'Results'],
    },
  },
  {
    id: 'nonprofit-director',
    name: 'Nonprofit Director',
    description: 'Mission-driven community leader',
    category: 'Nonprofit',
    icon: Heart,
    avatar: avatarPool[9],
    traits: {
      name: 'Angela Martinez',
      role: 'Executive Director',
      demographics: { age: '44', location: 'Phoenix, AZ', income: '$85,000', education: 'Master of Public Administration' },
      background: 'Led multiple successful fundraising campaigns.',
      personalityTraits: { openness: 80, conscientiousness: 85, extraversion: 70, agreeableness: 90, neuroticism: 30 },
      communicationStyle: 'Passionate, collaborative, story-driven',
      techSavvy: 50,
      preferredChannels: ['In-person', 'Email', 'Social media'],
      brandValues: ['Mission', 'Community', 'Integrity'],
    },
  },
  {
    id: 'security-analyst',
    name: 'Security Analyst',
    description: 'Vigilant protector of digital assets',
    category: 'Technology',
    icon: Shield,
    avatar: avatarPool[10],
    traits: {
      name: 'Kevin Park',
      role: 'Senior Security Analyst',
      demographics: { age: '32', location: 'Washington, DC', income: '$145,000', education: 'MS Cybersecurity' },
      background: 'Former NSA analyst, 8 years in cybersecurity.',
      personalityTraits: { openness: 55, conscientiousness: 95, extraversion: 30, agreeableness: 50, neuroticism: 65 },
      communicationStyle: 'Analytical, cautious, technical',
      techSavvy: 90,
      preferredChannels: ['Encrypted email', 'Slack', 'Incident calls'],
      brandValues: ['Security', 'Vigilance', 'Compliance'],
    },
  },
  {
    id: 'content-creator',
    name: 'Content Creator',
    description: 'Digital storyteller building audience',
    category: 'Media',
    icon: Mic,
    avatar: avatarPool[11],
    traits: {
      name: 'Lauren Brooks',
      role: 'YouTuber & Podcaster',
      demographics: { age: '26', location: 'Los Angeles, CA', income: '$120,000', education: 'Communications' },
      background: '1M+ subscribers, 3 years creating full-time content.',
      personalityTraits: { openness: 90, conscientiousness: 65, extraversion: 95, agreeableness: 75, neuroticism: 50 },
      communicationStyle: 'Authentic, enthusiastic, conversational',
      techSavvy: 80,
      preferredChannels: ['YouTube', 'Twitter', 'Discord'],
      brandValues: ['Authenticity', 'Entertainment', 'Connection'],
    },
  },
  {
    id: 'student',
    name: 'College Student',
    description: 'Ambitious learner navigating academics',
    category: 'Education',
    icon: GraduationCap,
    avatar: avatarPool[12],
    traits: {
      name: 'Jake Miller',
      role: 'Computer Science Student',
      demographics: { age: '21', location: 'Ann Arbor, MI', income: '$15,000', education: 'Junior at University of Michigan' },
      background: 'Dean List student, involved in coding clubs.',
      personalityTraits: { openness: 75, conscientiousness: 65, extraversion: 60, agreeableness: 70, neuroticism: 55 },
      communicationStyle: 'Casual, curious, collaborative',
      techSavvy: 85,
      preferredChannels: ['Discord', 'Slack', 'Text'],
      brandValues: ['Growth', 'Community', 'Innovation'],
    },
  },
  {
    id: 'real-estate-agent',
    name: 'Real Estate Agent',
    description: 'Trustworthy advisor closing deals',
    category: 'Business',
    icon: Building2,
    avatar: avatarPool[13],
    traits: {
      name: 'Susan Lee',
      role: 'Real Estate Agent',
      demographics: { age: '40', location: 'Miami, FL', income: '$120,000', education: 'Bachelor in Business' },
      background: 'Top performer in luxury homes market.',
      personalityTraits: { openness: 60, conscientiousness: 85, extraversion: 80, agreeableness: 75, neuroticism: 30 },
      communicationStyle: 'Professional, personable, persuasive',
      techSavvy: 65,
      preferredChannels: ['Phone', 'Email', 'Text'],
      brandValues: ['Trust', 'Expertise', 'Results'],
    },
  },
  {
    id: 'chef',
    name: 'Professional Chef',
    description: 'Culinary artist creating experiences',
    category: 'Food',
    icon: Utensils,
    avatar: avatarPool[14],
    traits: {
      name: 'Marco Rossi',
      role: 'Executive Chef',
      demographics: { age: '38', location: 'New Orleans, LA', income: '$95,000', education: 'Culinary Institute' },
      background: 'Michelin-starred restaurant experience.',
      personalityTraits: { openness: 85, conscientiousness: 90, extraversion: 55, agreeableness: 65, neuroticism: 40 },
      communicationStyle: 'Passionate, precise, artistic',
      techSavvy: 50,
      preferredChannels: ['In-person', 'Instagram', 'Email'],
      brandValues: ['Quality', 'Creativity', 'Tradition'],
    },
  },
  {
    id: 'scientist',
    name: 'Research Scientist',
    description: 'Curious mind discovering truths',
    category: 'Science',
    icon: FlaskConical,
    avatar: avatarPool[15],
    traits: {
      name: 'Dr. Priya Sharma',
      role: 'Research Scientist',
      demographics: { age: '35', location: 'Boston, MA', income: '$130,000', education: 'PhD in Biochemistry' },
      background: 'Published researcher in cancer treatments.',
      personalityTraits: { openness: 80, conscientiousness: 95, extraversion: 30, agreeableness: 70, neuroticism: 45 },
      communicationStyle: 'Analytical, careful, detail-oriented',
      techSavvy: 80,
      preferredChannels: ['Email', 'Slack', 'Conferences'],
      brandValues: ['Science', 'Rigor', 'Impact'],
    },
  },
  {
    id: 'pilot',
    name: 'Commercial Pilot',
    description: 'Sky-high professional with adventure',
    category: 'Travel',
    icon: Plane,
    avatar: avatarPool[16],
    traits: {
      name: 'Captain Tom Wilson',
      role: 'Commercial Pilot',
      demographics: { age: '44', location: 'Dallas, TX', income: '$185,000', education: 'Aviation Degree' },
      background: '12 years flying commercial routes.',
      personalityTraits: { openness: 65, conscientiousness: 95, extraversion: 50, agreeableness: 60, neuroticism: 25 },
      communicationStyle: 'Calm, professional, brief',
      techSavvy: 85,
      preferredChannels: ['Radio', 'Email', 'In-person'],
      brandValues: ['Safety', 'Precision', 'Adventure'],
    },
  },
  {
    id: 'gamer',
    name: 'Professional Gamer',
    description: 'Competitive esports player',
    category: 'Gaming',
    icon: Gamepad2,
    avatar: avatarPool[17],
    traits: {
      name: 'StarPlayer99',
      role: 'Pro Gamer',
      demographics: { age: '22', location: 'Seoul, Korea', income: '$250,000', education: 'High School' },
      background: 'World tournament champion.',
      personalityTraits: { openness: 70, conscientiousness: 75, extraversion: 65, agreeableness: 50, neuroticism: 60 },
      communicationStyle: 'Quick, strategic, competitive',
      techSavvy: 95,
      preferredChannels: ['Discord', 'Twitch', 'Twitter'],
      brandValues: ['Competition', 'Skill', 'Entertainment'],
    },
  },
  {
    id: 'writer',
    name: 'Freelance Writer',
    description: 'Wordsmith crafting stories',
    category: 'Media',
    icon: PenTool,
    avatar: avatarPool[18],
    traits: {
      name: 'Emma Collins',
      role: 'Freelance Writer',
      demographics: { age: '29', location: 'Portland, OR', income: '$65,000', education: 'English Degree' },
      background: 'Published author and blogger.',
      personalityTraits: { openness: 90, conscientiousness: 70, extraversion: 45, agreeableness: 75, neuroticism: 50 },
      communicationStyle: 'Descriptive, imaginative, emotive',
      techSavvy: 75,
      preferredChannels: ['Email', 'Social media', 'Video calls'],
      brandValues: ['Creativity', 'Authenticity', 'Voice'],
    },
  },
  {
    id: 'crypto-trader',
    name: 'Crypto Trader',
    description: 'Digital asset investor',
    category: 'Finance',
    icon: Bitcoin,
    avatar: avatarPool[19],
    traits: {
      name: 'Alex Crypto',
      role: 'DeFi Trader',
      demographics: { age: '27', location: 'Miami, FL', income: '$200,000', education: 'Self-taught' },
      background: 'Early Bitcoin investor, now full-time trader.',
      personalityTraits: { openness: 85, conscientiousness: 60, extraversion: 55, agreeableness: 45, neuroticism: 75 },
      communicationStyle: 'Technical, risk-aware, fast-paced',
      techSavvy: 95,
      preferredChannels: ['Twitter', 'Discord', 'Telegram'],
      brandValues: ['Innovation', 'Independence', 'Risk'],
    },
  },
  {
    id: 'teacher',
    name: 'School Teacher',
    description: 'Educator shaping futures',
    category: 'Education',
    icon: BookOpen,
    avatar: avatarPool[20],
    traits: {
      name: 'Mrs. Karen Johnson',
      role: 'High School Teacher',
      demographics: { age: '42', location: 'Chicago, IL', income: '$70,000', education: 'Master in Education' },
      background: '15 years teaching chemistry.',
      personalityTraits: { openness: 70, conscientiousness: 90, extraversion: 65, agreeableness: 85, neuroticism: 35 },
      communicationStyle: 'Encouraging, patient, clear',
      techSavvy: 60,
      preferredChannels: ['Email', 'In-person', 'Google Classroom'],
      brandValues: ['Education', 'Patience', 'Inspiration'],
    },
  },
  {
    id: 'ux-designer',
    name: 'UX Designer',
    description: 'User experience specialist',
    category: 'Design',
    icon: Laptop,
    avatar: avatarPool[21],
    traits: {
      name: 'Sophie Chen',
      role: 'Senior UX Designer',
      demographics: { age: '30', location: 'Seattle, WA', income: '$140,000', education: 'MFA in Interaction Design' },
      background: 'Designed for top tech companies.',
      personalityTraits: { openness: 85, conscientiousness: 80, extraversion: 55, agreeableness: 75, neuroticism: 35 },
      communicationStyle: 'Empathetic,user-centric, visual',
      techSavvy: 90,
      preferredChannels: ['Figma', 'Slack', 'User interviews'],
      brandValues: ['User focus', 'Simplicity', 'Accessibility'],
    },
  },
  {
    id: 'customer-support',
    name: 'Customer Support',
    description: 'Problem solver for customers',
    category: 'Service',
    icon: Headphones,
    avatar: avatarPool[22],
    traits: {
      name: 'Maria Garcia',
      role: 'Customer Support Lead',
      demographics: { age: '31', location: 'Phoenix, AZ', income: '$55,000', education: 'Associate Degree' },
      background: '5 years in tech support.',
      personalityTraits: { openness: 60, conscientiousness: 85, extraversion: 70, agreeableness: 80, neuroticism: 40 },
      communicationStyle: 'Empathetic, patient, solution-focused',
      techSavvy: 70,
      preferredChannels: ['Chat', 'Phone', 'Email'],
      brandValues: ['Support', 'Patience', 'Resolution'],
    },
  },
  {
    id: 'product-manager',
    name: 'Product Manager',
    description: 'Visionary driving product success',
    category: 'Business',
    icon: Target,
    avatar: avatarPool[23],
    traits: {
      name: 'Daniel Brown',
      role: 'Senior Product Manager',
      demographics: { age: '36', location: 'San Francisco, CA', income: '$175,000', education: 'MBA' },
      background: 'Launched multiple successful products.',
      personalityTraits: { openness: 75, conscientiousness: 85, extraversion: 65, agreeableness: 70, neuroticism: 40 },
      communicationStyle: 'Strategic, data-driven, collaborative',
      techSavvy: 85,
      preferredChannels: ['Slack', 'Jira', 'Strategy meetings'],
      brandValues: ['Vision', 'Impact', 'User value'],
    },
  },
  {
    id: 'influencer',
    name: 'Social Influencer',
    description: 'Digital trendsetter',
    category: 'Media',
    icon: MessageSquare,
    avatar: avatarPool[24],
    traits: {
      name: 'Chloe Rose',
      role: 'Lifestyle Influencer',
      demographics: { age: '24', location: 'Los Angeles, CA', income: '$180,000', education: 'Self-made' },
      background: '500K+ followers across platforms.',
      personalityTraits: { openness: 85, conscientiousness: 60, extraversion: 95, agreeableness: 70, neuroticism: 55 },
      communicationStyle: 'Authentic, engaging, trend-aware',
      techSavvy: 90,
      preferredChannels: ['Instagram', 'TikTok', 'YouTube'],
      brandValues: ['Authenticity', 'Influence', 'Connection'],
    },
  },
  {
    id: 'ecommerce-manager',
    name: 'E-commerce Manager',
    description: 'Online retail expert',
    category: 'Business',
    icon: ShoppingCart,
    avatar: avatarPool[25],
    traits: {
      name: 'Ryan Taylor',
      role: 'E-commerce Manager',
      demographics: { age: '33', location: 'New York, NY', income: '$110,000', education: 'Digital Marketing Cert' },
      background: 'Grew startup to 8-figure revenue.',
      personalityTraits: { openness: 70, conscientiousness: 85, extraversion: 60, agreeableness: 65, neuroticism: 45 },
      communicationStyle: 'Data-driven, strategic, metrics-focused',
      techSavvy: 85,
      preferredChannels: ['Email', 'Slack', ' Analytics tools'],
      brandValues: ['Growth', 'Conversion', 'Experience'],
    },
  },
  {
    id: 'videographer',
    name: 'Videographer',
    description: 'Visual storyteller',
    category: 'Media',
    icon: Video,
    avatar: avatarPool[26],
    traits: {
      name: 'Chris Martinez',
      role: 'Professional Videographer',
      demographics: { age: '28', location: 'Austin, TX', income: '$75,000', education: 'Film School' },
      background: 'Award-winning documentary filmmaker.',
      personalityTraits: { openness: 90, conscientiousness: 75, extraversion: 50, agreeableness: 65, neuroticism: 45 },
      communicationStyle: 'Visual, creative, story-driven',
      techSavvy: 80,
      preferredChannels: ['Email', 'Vimeo', 'In-person'],
      brandValues: ['Creativity', 'Story', 'Quality'],
    },
  },
  {
    id: 'data-analyst',
    name: 'Data Analyst',
    description: 'Numbers expert extracting insights',
    category: 'Technology',
    icon: Database,
    avatar: avatarPool[27],
    traits: {
      name: 'Lisa Wong',
      role: 'Data Analyst',
      demographics: { age: '29', location: 'Seattle, WA', income: '$115,000', education: 'MS Data Science' },
      background: 'Analytics lead at Fortune 500.',
      personalityTraits: { openness: 70, conscientiousness: 90, extraversion: 35, agreeableness: 65, neuroticism: 30 },
      communicationStyle: 'Analytical, precise, data-driven',
      techSavvy: 95,
      preferredChannels: ['Slack', 'Tableau', 'Email'],
      brandValues: ['Insight', 'Accuracy', 'Impact'],
    },
  },
  {
    id: 'devops-engineer',
    name: 'DevOps Engineer',
    description: 'Infrastructure automation expert',
    category: 'Technology',
    icon: Cpu,
    avatar: avatarPool[28],
    traits: {
      name: 'Patrick DevOps',
      role: 'DevOps Engineer',
      demographics: { age: '32', location: 'Denver, CO', income: '$155,000', education: 'Computer Engineering' },
      background: 'Built CI/CD pipelines at scale.',
      personalityTraits: { openness: 75, conscientiousness: 90, extraversion: 40, agreeableness: 60, neuroticism: 35 },
      communicationStyle: 'Technical, automated, efficient',
      techSavvy: 95,
      preferredChannels: ['Slack', 'GitHub', 'Jira'],
      brandValues: ['Automation', 'Reliability', 'Speed'],
    },
  },
  {
    id: 'photographer',
    name: 'Professional Photographer',
    description: 'Capturing moments artist',
    category: 'Creative',
    icon: Camera,
    avatar: avatarPool[29],
    traits: {
      name: 'Anna Lens',
      role: 'Professional Photographer',
      demographics: { age: '35', location: 'Nashville, TN', income: '$80,000', education: 'Art School' },
      background: 'Published in major magazines.',
      personalityTraits: { openness: 90, conscientiousness: 70, extraversion: 55, agreeableness: 70, neuroticism: 40 },
      communicationStyle: 'Visual, artistic, patient',
      techSavvy: 75,
      preferredChannels: ['Instagram', 'Email', 'In-person'],
      brandValues: ['Artistry', 'Moments', 'Creativity'],
    },
  },
  {
    id: 'mobile-developer',
    name: 'Mobile Developer',
    description: 'App builder for iOS and Android',
    category: 'Technology',
    icon: Smartphone,
    avatar: avatarPool[30],
    traits: {
      name: 'Kevin App',
      role: 'Mobile Developer',
      demographics: { age: '28', location: 'San Jose, CA', income: '$160,000', education: 'BS Computer Science' },
      background: 'Apps with 1M+ downloads.',
      personalityTraits: { openness: 80, conscientiousness: 85, extraversion: 45, agreeableness: 65, neuroticism: 35 },
      communicationStyle: 'Technical, mobile-first, user-focused',
      techSavvy: 95,
      preferredChannels: ['GitHub', 'Slack', 'App stores'],
      brandValues: ['Innovation', 'User experience', 'Performance'],
    },
  },
  {
    id: 'cloud-engineer',
    name: 'Cloud Engineer',
    description: 'Cloud architecture specialist',
    category: 'Technology',
    icon: Cloud,
    avatar: avatarPool[31],
    traits: {
      name: 'Sarah Cloud',
      role: 'AWS Solutions Architect',
      demographics: { age: '34', location: 'Remote', income: '$165,000', education: 'Cloud Certifications' },
      background: 'Architecting for enterprise.',
      personalityTraits: { openness: 75, conscientiousness: 90, extraversion: 40, agreeableness: 60, neuroticism: 30 },
      communicationStyle: 'Technical, scalable, secure',
      techSavvy: 95,
      preferredChannels: ['Slack', 'AWS console', 'Documentation'],
      brandValues: ['Scalability', 'Security', 'Reliability'],
    },
  },
  {
    id: 'mail-marketing',
    name: 'Email Marketer',
    description: 'Conversion optimization specialist',
    category: 'Marketing',
    icon: Mail,
    avatar: avatarPool[32],
    traits: {
      name: 'Tom Send',
      role: 'Email Marketing Manager',
      demographics: { age: '31', location: 'Atlanta, GA', income: '$85,000', education: 'Marketing Degree' },
      background: '40% conversion rate specialist.',
      personalityTraits: { openness: 65, conscientiousness: 85, extraversion: 55, agreeableness: 70, neuroticism: 40 },
      communicationStyle: 'Persuasive, data-driven, creative',
      techSavvy: 75,
      preferredChannels: ['Email platforms', 'A/B testing', 'Analytics'],
      brandValues: ['Conversion', 'Personalization', 'Testing'],
    },
  },
  {
    id: 'seo-specialist',
    name: 'SEO Specialist',
    description: 'Search optimization expert',
    category: 'Marketing',
    icon: Search,
    avatar: avatarPool[33],
    traits: {
      name: 'Rachel SEO',
      role: 'SEO Specialist',
      demographics: { age: '27', location: 'Chicago, IL', income: '$90,000', education: 'Digital Marketing' },
      background: 'Ranked sites #1 for competitive keywords.',
      personalityTraits: { openness: 70, conscientiousness: 90, extraversion: 45, agreeableness: 60, neuroticism: 45 },
      communicationStyle: 'Analytical, strategic, growth-focused',
      techSavvy: 80,
      preferredChannels: ['Google Analytics', 'Slack', 'Reports'],
      brandValues: ['Rankings', 'Traffic', 'Growth'],
    },
  },
  {
    id: 'social-media-manager',
    name: 'Social Media Manager',
    description: 'Building online communities',
    category: 'Marketing',
    icon: Globe,
    avatar: avatarPool[34],
    traits: {
      name: 'Jessica Social',
      role: 'Social Media Manager',
      demographics: { age: '28', location: 'Los Angeles, CA', income: '$75,000', education: 'Communications' },
      background: 'Grew following 10x for brands.',
      personalityTraits: { openness: 85, conscientiousness: 70, extraversion: 80, agreeableness: 75, neuroticism: 50 },
      communicationStyle: 'Engaging, trend-aware, community-focused',
      techSavvy: 80,
      preferredChannels: ['Social platforms', 'Scheduling tools', 'Analytics'],
      brandValues: ['Engagement', 'Community', 'Content'],
    },
  },
  {
    id: 'recruiter',
    name: 'Tech Recruiter',
    description: 'Talent acquisition specialist',
    category: 'HR',
    icon: Users,
    avatar: avatarPool[35],
    traits: {
      name: 'Amanda Hire',
      role: 'Technical Recruiter',
      demographics: { age: '33', location: 'Austin, TX', income: '$95,000', education: 'HR Degree' },
      background: 'Placed 200+ tech candidates.',
      personalityTraits: { openness: 65, conscientiousness: 85, extraversion: 75, agreeableness: 80, neuroticism: 35 },
      communicationStyle: 'Personable, consultative, relationship-focused',
      techSavvy: 65,
      preferredChannels: ['LinkedIn', 'Phone', 'Email'],
      brandValues: ['Matching', 'Trust', 'Career growth'],
    },
  },
  {
    id: 'hr-manager',
    name: 'HR Manager',
    description: 'People and culture leader',
    category: 'HR',
    icon: Award,
    avatar: avatarPool[36],
    traits: {
      name: 'Jennifer Culture',
      role: 'HR Manager',
      demographics: { age: '38', location: 'Portland, OR', income: '$100,000', education: 'HR Management' },
      background: 'Built inclusive culture programs.',
      personalityTraits: { openness: 80, conscientiousness: 85, extraversion: 70, agreeableness: 90, neuroticism: 30 },
      communicationStyle: 'Empathetic, policy-minded, growth-focused',
      techSavvy: 65,
      preferredChannels: ['1:1 meetings', 'Email', 'HR systems'],
      brandValues: ['People', 'Growth', 'Inclusion'],
    },
  },
  {
    id: 'freelance-consultant',
    name: 'Freelance Consultant',
    description: 'Independent business advisor',
    category: 'Business',
    icon: Zap,
    avatar: avatarPool[37],
    traits: {
      name: 'Patricia Smart',
      role: 'Business Consultant',
      demographics: { age: '45', location: 'Charlotte, NC', income: '$150,000', education: 'MBA' },
      background: 'Helped 50+ startups scale.',
      personalityTraits: { openness: 75, conscientiousness: 90, extraversion: 60, agreeableness: 70, neuroticism: 25 },
      communicationStyle: 'Strategic, expert, Results-oriented',
      techSavvy: 75,
      preferredChannels: ['Zoom', 'Email', 'LinkedIn'],
      brandValues: ['Strategy', 'Results', 'Expertise'],
    },
  },
  {
    id: 'coffee-shop-owner',
    name: 'Coffee Shop Owner',
    description: 'Community café entrepreneur',
    category: 'Food',
    icon: Coffee,
    avatar: avatarPool[38],
    traits: {
      name: 'Beth Brew',
      role: 'Café Owner',
      demographics: { age: '36', location: 'Asheville, NC', income: '$55,000', education: 'Barista Training' },
      background: ' neighborhood favorite for 8 years.',
      personalityTraits: { openness: 80, conscientiousness: 80, extraversion: 75, agreeableness: 85, neuroticism: 30 },
      communicationStyle: 'Warm, community-focused, quality-focused',
      techSavvy: 50,
      preferredChannels: ['In-person', 'Social media', 'Word of mouth'],
      brandValues: ['Quality', 'Community', 'Sustainability'],
    },
  },
];

export const Templates = () => {
  const { addPersona, setActivePersona, showToast } = useStore();

  const handleUseTemplate = (template: typeof templates[0]) => {
    const now = new Date().toISOString();
    const newPersona: Persona = {
      ...getDefaultPersona(),
      ...template.traits,
      avatar: template.avatar,
      id: crypto.randomUUID(),
      createdAt: now,
      updatedAt: now,
      goals: [],
      painPoints: [],
      motivations: [],
      behaviors: [],
      quote: '',
      brandValues: template.traits.brandValues || [],
      preferredChannels: template.traits.preferredChannels || [],
      preferredTone: '',
    };
    addPersona(newPersona);
    setActivePersona(newPersona.id);
    showToast(`${template.name} template applied!`);
  };

  return (
    <div className="space-y-6">
      <div>
        <h1 className="font-display text-3xl font-semibold text-[var(--text)]">Templates</h1>
        <p className="text-[var(--text-secondary)] mt-1">Start with a pre-built persona template</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4">
        {templates.map((template, index) => {
          const Icon = template.icon;
          return (
            <div
              key={template.id}
              className="card p-4 animate-fade-in-up"
              style={{ animationDelay: `${index * 0.05}s` }}
            >
              <div className="flex items-center justify-between mb-3">
                <span className="chip text-xs">{template.category}</span>
                <Icon className="w-4 h-4 text-[var(--text-secondary)]" />
              </div>
              <div className="flex items-center gap-3 mb-3">
                <img 
                  src={template.avatar} 
                  alt={template.name}
                  className="w-12 h-12 rounded-xl object-cover"
                  onError={(e) => {
                    e.currentTarget.style.display = 'none';
                    e.currentTarget.nextElementSibling?.classList.remove('hidden');
                  }}
                />
                <div className="hidden w-12 h-12 rounded-xl bg-[var(--accent)] flex items-center justify-center text-white font-medium text-sm">
                  {template.traits.name.split(' ').map(n => n[0]).join('')}
                </div>
                <div className="min-w-0">
                  <p className="font-medium text-[var(--text)] truncate">{template.traits.name}</p>
                  <p className="text-xs text-[var(--text-secondary)] truncate">{template.traits.role}</p>
                </div>
              </div>
              <p className="text-xs text-[var(--text-secondary)] line-clamp-2 mb-3">{template.description}</p>
              <button
                onClick={() => handleUseTemplate(template)}
                className="w-full btn-primary text-sm py-2"
              >
                Use Template
              </button>
            </div>
          );
        })}
      </div>
    </div>
  );
};